apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiv2
  template:
    metadata:
      labels:
        type: api
        tier: backend
        app: apiv2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - external
      containers:
      - image: public-registry.caliopen.org/caliopen_apiv2
        name: apiv2
        imagePullPolicy: Always
        ports:
        - containerPort: 31415
        volumeMounts:
        - name: apiv2-conf-volume
          mountPath: /etc/caliopen/apiv2.yaml
          subPath: apiv2.yaml
        - name: swagger-conf-volume
          mountPath: /etc/caliopen/swagger.json
          subPath: swagger.json
        - name: ca-certs
          mountPath: /etc/ssl/certs
      volumes:
      - name: apiv2-conf-volume
        configMap:
          name: apiv2-config
          items:
          - key: apiv2.yaml
            path: apiv2.yaml
      - name: swagger-conf-volume
        configMap:
          name: swagger-config
          items:
          - key: swagger.json
            path: swagger.json
      - name: ca-certs
        configMap:
          name: ca-certs
          items:
          - key: alpha.caliopen.org.crt
            path: alpha.caliopen.org.crt
          - key: beta.caliopen.org.crt
            path: beta.caliopen.org.crt
          - key: ca-certificates.crt
            path: ca-certificates.crt
      restartPolicy: Always
