---
- name: create namespace monitoring
  shell: kubectl create namespace monitoring

- name: create dashboard
  shell: kubectl apply -f {{ yaml_url }}/monitoring/{{ item }}.yaml
  with_items:
    - dashboard
  tags: dashboard

- include: config_pipeline.yml

- name: create logging deployments
  shell: kubectl apply -f {{ yaml_url }}/monitoring/{{ item }}.yaml -n monitoring
  with_items:
    - filebeat
    - logstash
  tags: logging

- include: config_prometheus.yml

- name: kube-system metric deployments
  shell: kubectl apply -f {{ yaml_url }}/monitoring/{{ item }}.yaml -n {{ prod_namespace }}
  with_items:
    - metrics-server
  tags: monitoring

- name: monitoring deployments
  shell: kubectl apply -f {{ yaml_url }}/monitoring/{{ item }}.yaml -n monitoring
  with_items:
    - prometheus
  tags: monitoring
