- name: Ensures {{ caliopen_config_path }} dir exists
  file: path={{ caliopen_config_path }} state=directory
  tags: config

- name: copy caliopen configs
  template:
    src: "{{ item }}"
    dest: "{{ caliopen_config_path }}"
    owner: "root"
    mode: 0600
  with_fileglob:
    - "templates/configs/*"
  tags: config

- name: create caliopen configs
  shell: kubectl create configmap {{ name }}-config --from-file={{ name }}.{{ ext }} -n {{ prod_namespace }}
  with_items:
    - { name: "apiv1", ext: "ini"}
    - { name: "apiv2", ext: "yaml"}
    - { name: "caliopen", ext: "yaml"}
    - { name: "idpoller", ext: "yaml"}
    - { name: "imapworker", ext: "yaml"}
    - { name: "lmtp", ext: "yaml"}
    - { name: "swagger", ext: "json"}
    - { name: "twitterworker", ext: "yaml"}
  ignore_errors: yes
  tags: config

- name: create frontend configmap
  shell: kubectl create configmap frontend-config --from-literal=api_hostname=api.{{ caliopen_domain_name }} --from-literal=api_protocol=https --from-literal=api_port=443 -n {{ prod_namespace }}
  tags: config

- name: create system configs
  shell: kubectl apply -f {{ yaml_url }}/configs/{{ item }}-config.yaml
  with_items:
    - coredns
  tags: [ config, system ]
