#polling config
scan_interval: 180                              # in minutes. How often storage is scanned to sync with remote identities data
remote_protocols:                               # which kind of remote protocols poller must handle
  - email
  - imap
  - twitter
#storage facility
store_name: cassandra                           # backend for remote identities data
store_settings:
  hosts: # many allowed
{% for host in groups['store'] %}
    - {{ hostvars[host]['private_ips'][0] }}
{% endfor %}
  keyspace: caliopen
  consistency_level: 1
#messaging system
nats_url: nats://{{ hostvars['mq1']['private_ips'][0] }}:4222
nats_queue : IDpoller
nats_topics:                                 # NATS topics to work with
  id_cache: idCache                          # receiving orders to update poller's cache
  imap: imapJobs                             # receiving requests for IMAP jobs
  twitter: twitterJobs                       # receiving requests for Twitter jobs