## SMTP config ##
AppConfig:
  allowed_hosts:
  - localhost
  - caliopen.local
  - {{ caliopen_domain_name }}
  primary_mail_host: {{ caliopen_domain_name }}
  inbound_servers: # only one allowed for now
  - is_enabled: true
    host_name: localhost
    max_size: 20971520                                   # max authorized size for emails in bytes
    timeout: 180
    listen_interface: 0.0.0.0:2525
    start_tls_on: false
    tls_always_on: false
    max_clients: 1000
  #submit is the MTA to connect to for final delivery (postfix for example)
  submit_address: mail1.local   # XXX hardcoded, can't use list
  submit_port: 587
  submit_user:
  submit_password:
  submit_workers: 2                                      # number of concurrent connexions to submit MTA

## LDA (Email broker) config ##
LDAConfig:
  broker_type: smtp                                      # types are : smtp, imap, mailboxe, etc.
  nats_url: nats://{{ hostvars['mq1']['backend_ip'] }}:4222
  nats_queue: SMTPqueue                                  # NATS group queue for nats subscribers to share jobs
  store_name: cassandra                                  # backend to store raw emails and messages (inbound & outbound)
  store_settings:
    hosts: # many allowed
{% for host in groups['store'] %}
      - {{ hostvars[host]['backend_ip'] }}
{% endfor %}
    keyspace: caliopen
    consistency_level: 1
    raw_size_limit: 1048576                              # max size in bytes for objects in db. Use S3 interface if larger.
    object_store: s3
    object_store_settings:
      endpoint: {{ hostvars['object_store1']['backend_ip'] }}:9000
      access_key: {{ object_store_access_key }}
      secret_key: {{ object_store_secret_key }}
      location: eu-fr-paris
      buckets:
        raw_messages: caliopen-raw-messages                # bucket name to put raw messages to
        temporary_attachments: caliopen-tmp-attachments    # bucket name to store draft attachments
  index_name: elasticsearch                              # backend to index messages (inbound & outbound)
  index_settings:
    urls: # many allowed
{% for host in groups['store'] %}
      - http://{{ hostvars[host]['backend_ip'] }}:9200
{% endfor %}

  #inbound
  in_topic: inboundSMTP # NATS topic to listen to
  lda_workers_size: 2                                    # number of concurrent workers
  log_received_mails: true

  # outbound
  out_topic: outboundSMTP                                # NATS topic to listen to
  nats_listeners: 2                                      # number of concurrent nats listeners

  # notifications
  contacts_topic: contactAction
  NotifierConfig:
    base_url: https://{{ caliopen_domain_name }}
    admin_username: admin
    templates_path: "/etc/caliopen/notifiers/templates/"
