workers:Â 10
twitter_app_key: {{ twitter_oauth_app_key }}
twitter_app_secret: {{ twitter_oauth_app_secret }}
BrokerConfig:
  #messaging system
  nats_url: nats://{{ hostvars['mq1']['private_ips'] }}:4222
  nats_queue: Twitterworkers                             # NATS group queue for workers
  nats_topic_poller: twitterJobs                         # NATS topic on which to request job from idpoller
  nats_topic_poller_cache: idCache                       # NATS topic to send orders to idpoller regarding identities management
  nats_topic_direct_message: twitter_dm                  # NATS topic to listen to orders for handling DMs (fetch, send)
  #storage facility
  store_name: cassandra                                  # backend to store raw emails and messages (inbound & outbound)
  store_settings:
    hosts: # many allowed
{% for host in groups['store'] %}
      - {{ hostvars[host]['private_ips'] }}
{% endfor %}
    keyspace: caliopen
    consistency_level: 1
    raw_size_limit: 1048576                                 # max size in bytes for objects in db. Use S3 interface if larger.
    object_store: s3
    object_store_settings:
      endpoint: {{ hostvars['object-store1']['private_ips'] }}:9000
      access_key: {{ object_store_access_key }}
      secret_key: {{ object_store_secret_key }}
      location: eu-fr-paris                                # S3 region.
      buckets:
        raw_messages: caliopen-raw-messages                # bucket name to put raw messages to
        temporary_attachments: caliopen-tmp-attachments    # bucket name to store draft attachments
    use_vault: true
    vault_settings:
      url: https://vault.{{ caliopen_domain_name }}:8200
      username: {{ vault_worker_username }}
      password: {{ vault_worker_password }}
  LDAConfig:
    broker_type: twitter                                   # types are : smtp, imap, mailboxe, etc.
    #index facility
    index_name: elasticsearch                              # backend to index messages (inbound & outbound)
    index_settings:
      urls: # many allowed
{% for host in groups['store'] %}
      - http://{{ hostvars[host]['private_ips'] }}:9200
{% endfor %}
    #messaging system
    in_topic: inboundTwitter
    # notifications
    NotifierConfig:
      admin_username: admin                                # username on whose behalf notifiers will act. This admin user must have been created before by other means.